// @ts-check

/**
 * This file is .mjs because it is also imported by cli.mjs
 *
 * These settings are explicitly added to the config generated by the CLI. This
 * is because these settings are highly likely to be customized by the user.
 * Technically *any* setting can be customized by the user, but exposing these
 * makes the job that much easier and transparent.
 */

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

/**
 * https://next.biomejs.dev/reference/configuration/#files
 *
 * @type {{
 *  ignoreUnknown?: boolean
 *  includes?: string[],
 *  maxSize?: number
 * }}
 */
export const files = {
  ignoreUnknown: true,
  includes: [
    '**', // Include all known files in all folders recursively.
    '!**/node_modules/**',
    '!dist/**',
    '!*.lock',
  ],
  // maxSize: 1048576, // Default value - (1024*1024, 1MB)
}
