// @ts-check

/**
 * This file is .mjs because it is also imported by cli.mjs
 *
 * These settings are explicitly added to the config generated by the CLI. This
 * is because these settings are highly likely to be customized by the user.
 * Technically *any* setting can be customized by the user, but exposing these
 * makes the job that much easier and transparent.
 */

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

/**
 * https://next.biomejs.dev/reference/configuration/#files
 *
 * @type {{
 *  ignoreUnknown?: boolean
 *  includes?: string[],
 *  maxSize?: number
 * }}
 */
export const files = {
  ignoreUnknown: true,

  /**
   * '!dist'  - don't lint/format it, but the scanner may still index it
   * '!!dist' - don't even look at it, period
   * 
   * The scanner follows import chains. So if a source file imports from
   * 'dist/some-file.ts', Biome will still index that file to resolves types and
   * a few other things.
   */
  includes: ['**', '!**/node_modules', '!dist', '!*.lock'],
  // maxSize: 1048576, // Default value - (1024*1024, 1MB)
}
